### ISSUE TITLE
Formatting `.liquid` files deletes their contents

### ISSUE THREAD

**Issue by joshistoast** [Shopify/theme-tools#358]
**Describe the bug**

When both the extension itself and `formatOnSave` is enabled on liquid files, the entire file is wiped on save.

An issue for this existed but was prematurely closed: #327 

**Source**
Any `.liquid` file

**Expected behavior**

Formatting the file

**Actual behavior**

Deletes all contents of the file

**Debugging information**
 - OS: MacOS 14.4.1
 - Theme Check Version: 2.3.2

**Additional context**

Setting `formatOnSave` to `false` prevents further deletions of file contents, but doesn't format any files.
```json
{
  ...
  "[liquid]": {
    "editor.defaultFormatter": "Shopify.theme-check-vscode",
    "editor.formatOnSave": false
  },
  ...
}
```

**Comment by mgmanzella** [comment]
hi @joshistoast , thanks for reporting this issue 🙏 to confirm, is this happening for all liquid files or just certain ones?? because this doesn't appear to be broken for everyone, this is our current suspicion:

if it’s happening on all liquid files
- it’s likely an environment issue
- it can be an issue in the vscode-extension or possibly a conflict with another extension (as mentioned [here](https://github.com/Shopify/theme-tools/issues/327#issuecomment-2012098535))

if it’s happening only in some liquid files
- it’s likely an issue in parser/formatter, then we can get the asset name to reproduce ourselves

lastly if you could share your extension logs, that would also give us more insight about the issue. here's how you can do it in vs code:


![getting-logs](https://github.com/Shopify/theme-tools/assets/18431672/346e607e-09ed-4d29-a63b-1e4cad91e16a)


thanks in advance for your help as we investigate

**Comment by joshistoast** [comment]
@mgmanzella 
Within my `settings.json`
```json
"[liquid]": {
  "editor.defaultFormatter": "Shopify.theme-check-vscode",
  "editor.formatOnSave": true
},
```

https://github.com/Shopify/theme-tools/assets/23065423/8509dc3b-a7ee-494a-abe6-0a3497d6264a

The issue is immediately resolved when setting `editor.formatOnSave` to `false`

**Comment by mgmanzella** [comment]
appreciate you sharing that but could you please answer the questions in my previous comment, we need this information to understand what's happening. thanks 🙏

**Comment by joshistoast** [comment]
> appreciate you sharing that but could you please answer the questions in my previous comment, we need this information to understand what's happening. thanks 🙏

Apologies, it happens in every liquid file

**Comment by joshistoast** [comment]
@mgmanzella language server logs should be in the video on the bottom half of the window.

> an additional workaround you can try is deactivating other extensions and see if the issue still persists, keep us posted tho

Did this also but to no avail, but uninstalling the shopify extension in question did solve it.

**Comment by mgmanzella** [comment]
> language server logs should be in the video on the bottom half of the window.

ahhh you're right my bad, do you mind sending the raw logs from language server?? if you dont feel comfortable doing that publicly, feel free to DM me on the partners slack `@Morisa Manzella`

> Did this also but to no avail, but uninstalling the shopify extension in question did solve it.

right which removes liquid prettier from vs code 😭 

we'll investigate thanks again for raising 🙏

**Comment by joshistoast** [comment]
Update, editor update on save set to false and my file is still being wiped.

**Comment by charlespwd** [comment]
More context: https://github.com/Shopify/theme-tools/issues/586#issuecomment-2476780957

Maybe it's WSL related? How is this happening? We're supposed to not do anything when there's an error. Why would `prettier.format` return the empty string without error?

**Comment by jpallard6120** [comment]
@charlespwd Thanks for moving this here! Happy to give more context if necessary.

**Comment by jpallard6120** [comment]
I tried deleting .prettierrc, but it just removed the ability to format through Shopify Theme Check. 

I don't have anything super weird in the window group, apart from these lines maybe? 

```
2024-11-26 14:37:05.548 [warning] [backup tracker] suspended, ignoring unregister event vscode-remote://wsl%2Bubuntu-22.04/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/package.json 
```

Funnily enough, I had an actual error within a test of a file with a syntax error, so it means Theme Check does get the data correctly: 

```
2024-11-26 14:32:37.977 [error] [Extension Host] LiquidHTMLParsingError: Line 74, col 22: expected not an identifierCharacter, "}}", "%}", "-}}", or "-%}"
  72 |         {%- unless is_month -%}
  73 |         {{ parent_tag | strip }},
> 74 |         {%- endunless- %}
     |                      ^
  75 |       {%- endfor -%}
  76 |      {%- endcapture -%}
  77 |       {% for article in blog.articles offset: 1 %}
	at toCST (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:46922:15)
	at toLiquidHtmlCST (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:46892:12)
	at toLiquidHtmlAST (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:47633:51)
	at Object.parse (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:49408:53)
	at Object.parse (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/index.js:7515:23)
	at coreFormat (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/index.js:8829:18)
	at formatWithCursor2 (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/index.js:9021:18)
	at /home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/index.js:38183:12
	at Object.format (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/prettier/index.js:38197:12)
	at nodePrettierFormat (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:19014:21)
	at async LiquidFormatter.toTextEdit (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:18833:27)
	at async LiquidFormatter.provideDocumentFormattingEdits (/home/wake/.vscode-server/extensions/shopify.theme-check-vscode-3.1.0/dist/node/extension.js:18823:32)
	at async g$.provideDocumentFormattingEdits (file:///home/wake/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:137:134090)
```

On another file without the syntax error, the file is wiped as usual, and nothing is logged in the Window group.

**Comment by charlespwd** [comment]
> On another file without the syntax error, the file is wiped as usual, and nothing is logged in the Window group.

Makes sense. Would only happen if textEdit sent an empty string as a TextEdit...

This is definitely some ghostbusters kind of issue.

So... 
- we got that parsing blocks pretty-printing if it errors out
- we got that somehow we print an empty string (or is it invalid text position?)

I wonder...
- Encoding maybe (not utf8?)?
- Windows/linux newlines? (`\r\n`?)

**Comment by prakharaug** [comment]
I am facing this issue. Is this resolved ??
